[package]
name = "day03"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "part1"

[[bin]]
name = "part2"

[[bench]]
name = "part2_bench"
harness = false

[dependencies]
anyhow.workspace = true
utils = { path = "../utils" }
rayon.workspace = true

[dev-dependencies]
criterion.workspace = true
