[package]
name = "day01"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
nom.workspace = true
utils = { path = "../utils" }

[[bin]]
name = "part1"
test = true

[[bin]]
name = "part2"
test = true
